"""World Protocol — the abstract surface every backend must implement.

Decision core takes World as a dependency and runs identically against
`SimWorld` (in-memory) and `RealWorld` (gh + git + filesystem, v2).
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol, runtime_checkable

from lemmings.schemas import (
    PR,
    LedgerRow,
    ReviewResult,
    Ticket,
    TicketStatus,
)


@runtime_checkable
class World(Protocol):
    """Abstract pipeline state. Pure read/write — no decision logic here."""

    # --- Tickets ---
    def add_ticket(self, ticket: Ticket) -> None: ...
    def get_ticket(self, ticket_id: str) -> Ticket: ...
    def update_ticket_status(self, ticket_id: str, status: TicketStatus) -> None: ...
    def list_tickets(self, status: TicketStatus | None = None) -> list[Ticket]: ...

    # --- PRs ---
    def open_pr(self, pr: PR) -> None: ...
    def get_pr(self, ticket_id: str) -> PR | None: ...
    def list_open_prs(self) -> list[PR]: ...
    def close_pr(self, ticket_id: str, merged: bool) -> None: ...

    # --- Reviews ---
    def record_review(self, result: ReviewResult) -> None: ...
    def list_reviews(self, ticket_id: str) -> list[ReviewResult]: ...

    # --- Cost ledger ---
    def append_ledger(self, row: LedgerRow) -> None: ...
    def ledger_rows(self) -> Iterable[LedgerRow]: ...
    def total_billed_usd(self) -> float: ...

    # --- Sprint metadata ---
    def sprint_budget_usd(self) -> float: ...
    def set_sprint_budget_usd(self, value: float) -> None: ...
    def is_budget_locked(self) -> bool: ...
    def lock_budget(self, reason: str) -> None: ...
