#!/usr/bin/env python3
"""Sync AI coding tool configurations from canonical source.

Reads rules from .dev-context/rules/ and project context from CLAUDE.md,
then generates/validates tool-specific configs for Cursor, Antigravity,
and the cross-tool AGENTS.md standard.

Usage:
    python scripts/sync-tool-configs.py --check   # Report drift (CI-safe)
    python scripts/sync-tool-configs.py --sync    # Regenerate all configs
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

GENERATED_HEADER_MD = "<!-- Generated by scripts/sync-tool-configs.py — do not edit directly -->"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = PROJECT_ROOT / ".dev-context" / "rules"
CURSOR_RULES_DIR = PROJECT_ROOT / ".cursor" / "rules"
ANTIGRAVITY_RULES_DIR = PROJECT_ROOT / ".antigravity" / "rules"

# Mapping: source rule file -> Cursor .mdc metadata
CURSOR_RULE_CONFIG: dict[str, dict[str, str | bool]] = {
    "general.md": {
        "description": "Code quality limits, naming conventions, logging",
        "alwaysApply": True,
    },
    "git.md": {
        "description": "Git workflow: conventional commits, branching, PR",
        "alwaysApply": True,
    },
    "python.md": {
        "description": "Python 3.12+ rules: FastAPI, SQLAlchemy, Pydantic",
        "globs": "**/*.py",
    },
    "testing.md": {
        "description": "Testing: pytest-asyncio, mocking, coverage",
        "globs": "tests/**/*.py",
    },
    "security.md": {
        "description": "Security: auth, validation, injection prevention",
        "globs": "app/**/*.py",
    },
    "parallel-dev.md": {
        "description": "Parallel development: worktrees, sync protocol",
        "alwaysApply": True,
    },
    "planning-gate.md": {
        "description": "Planning gate: no coding a ticket until estimated + model-routed",
        "alwaysApply": True,
    },
    "labeling.md": {
        "description": "ML-ready ticket labeling: typed dimensions + taxonomy extension point",
        "alwaysApply": True,
    },
    "iteration-gate.md": {
        "description": "Iteration gate: only code a tracked, in-iteration ticket (HARD-STOP)",
        "alwaysApply": True,
    },
    "verify-claim.md": {
        "description": "Pre-PR verify-claim guard: trace data sources on relabels + new warnings",
        "alwaysApply": True,
    },
    "rails.md": {
        "description": "Rail R/U manifestation contract: merged tickets leave evidence",
        "alwaysApply": True,
    },
}


def content_hash(text: str) -> str:
    """Return first 12 chars of SHA-256 hash of normalized content."""
    normalized = text.strip().replace("\r\n", "\n")
    return hashlib.sha256(normalized.encode()).hexdigest()[:12]


def strip_generated_header(text: str) -> str:
    """Remove generated headers and source comments from text."""
    lines = text.split("\n")
    filtered = [
        line
        for line in lines
        if not line.startswith("<!-- Generated by")
        and not line.startswith("<!-- Source of truth:")
    ]
    return "\n".join(filtered).strip()


def read_source_rule(name: str) -> str:
    """Read a rule file from .dev-context/rules/."""
    path = RULES_DIR / name
    if not path.exists():
        print(f"ERROR: Source rule not found: {path}")
        sys.exit(1)
    return path.read_text()


def build_cursor_mdc(rule_name: str, source: str) -> str:
    """Build a Cursor .mdc file from source rule + metadata."""
    config = CURSOR_RULE_CONFIG.get(rule_name, {})
    desc = config.get("description", rule_name.replace(".md", ""))
    globs = config.get("globs")
    always = config.get("alwaysApply", False)

    frontmatter = f'---\ndescription: "{desc}"\n'
    if globs:
        frontmatter += f'globs: "{globs}"\n'
    if always:
        frontmatter += "alwaysApply: true\n"
    frontmatter += "---"

    header = f"{GENERATED_HEADER_MD}\n<!-- Source of truth: .dev-context/rules/{rule_name} -->"

    return f"{frontmatter}\n{header}\n\n{source.strip()}\n"


def build_antigravity_rule(rule_name: str, source: str) -> str:
    """Build an Antigravity rule file from source rule."""
    header = f"{GENERATED_HEADER_MD}\n<!-- Source of truth: .dev-context/rules/{rule_name} -->"
    return f"{header}\n\n{source.strip()}\n"


def check_drift() -> list[str]:
    """Check if generated files are in sync with sources."""
    drifted: list[str] = []

    for rule_name in CURSOR_RULE_CONFIG:
        source = read_source_rule(rule_name)
        source_hash = content_hash(source)

        # Check Cursor
        mdc_name = rule_name.replace(".md", ".mdc")
        cursor_path = CURSOR_RULES_DIR / mdc_name
        if not cursor_path.exists():
            drifted.append(f"MISSING: {cursor_path}")
        else:
            cursor_content = strip_generated_header(cursor_path.read_text())
            # Strip frontmatter from cursor content for comparison
            if "---" in cursor_content:
                parts = cursor_content.split("---", 2)
                cursor_body = parts[2].strip() if len(parts) >= 3 else cursor_content
            else:
                cursor_body = cursor_content

            if content_hash(source) != content_hash(cursor_body):
                drifted.append(
                    f"DRIFT: {cursor_path} "
                    f"(source={source_hash}, "
                    f"generated={content_hash(cursor_body)})"
                )

        # Check Antigravity
        ag_path = ANTIGRAVITY_RULES_DIR / rule_name
        if not ag_path.exists():
            drifted.append(f"MISSING: {ag_path}")
        else:
            ag_content = strip_generated_header(ag_path.read_text())
            if content_hash(source) != content_hash(ag_content):
                drifted.append(
                    f"DRIFT: {ag_path} "
                    f"(source={source_hash}, "
                    f"generated={content_hash(ag_content)})"
                )

    return drifted


def sync_all() -> int:
    """Regenerate all tool-specific configs from source."""
    CURSOR_RULES_DIR.mkdir(parents=True, exist_ok=True)
    ANTIGRAVITY_RULES_DIR.mkdir(parents=True, exist_ok=True)

    count = 0
    for rule_name in CURSOR_RULE_CONFIG:
        source = read_source_rule(rule_name)

        # Cursor
        mdc_name = rule_name.replace(".md", ".mdc")
        cursor_path = CURSOR_RULES_DIR / mdc_name
        cursor_path.write_text(build_cursor_mdc(rule_name, source))
        count += 1

        # Antigravity
        ag_path = ANTIGRAVITY_RULES_DIR / rule_name
        ag_path.write_text(build_antigravity_rule(rule_name, source))
        count += 1

    print(f"Synced {count} files from {len(CURSOR_RULE_CONFIG)} source rules")
    return count


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync AI tool configs from .dev-context/rules/")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--check",
        action="store_true",
        help="Check for drift without modifying files",
    )
    group.add_argument(
        "--sync",
        action="store_true",
        help="Regenerate all tool configs from source",
    )
    args = parser.parse_args()

    if args.check:
        drifted = check_drift()
        if drifted:
            print("Tool configs out of sync with source:")
            for item in drifted:
                print(f"  {item}")
            print("\nRun 'python scripts/sync-tool-configs.py --sync' to regenerate.")
            sys.exit(1)
        else:
            print("All tool configs in sync.")
            sys.exit(0)

    if args.sync:
        sync_all()
        # Verify after sync
        drifted = check_drift()
        if drifted:
            print("WARNING: Drift detected after sync:")
            for item in drifted:
                print(f"  {item}")
            sys.exit(1)
        print("All tool configs in sync.")


if __name__ == "__main__":
    main()
